version: '3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass "redis" --maxmemory 2mb
    volumes:
      - cache:/data
  postgres:
    image: postgres:14.2-alpine

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=redis-opt
  pgadmin:
    container_name: "redisoptis_pgadmin"
    ports:
      - 5454:5454
    environment:
      - PGADMIN_DEFAULT_EMAIL=eleni@mailsac.com
      - PGADMIN_DEFAULT_PASSWORD=eleni
      - PGADMIN_LISTEN_PORT=5454
    image: 'dpage/pgadmin4:6.1'
    depends_on:
      - postgres
    links:
      - 'postgres:pgsql-server'
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.35.0
    network_mode: host
    container_name: prometheus
    ports:
    - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-lifecycle'
volumes:
  cache:
    driver: local


