spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/redis-opt
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true


server:
    port: 8081


management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus


